apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: shopmicro
data:
  loki.yaml: |-
    # from infrastructure/loki/loki-official.yaml
    server:
      http_listen_port: 3100

    auth_enabled: false

    common:
      path_prefix: /tmp/loki   # <-- ADD THIS
      storage:
        filesystem:
          chunks_directory: /tmp/loki/chunks
          rules_directory: /tmp/loki/rules
      replication_factor: 1
      ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: inmemory

    # query_range:
    #   results_cache:
    #     cache:
    #       embedded_cache:
    #         enabled: true
    #         max_size_mb: 100

    schema_config:
      configs:
        - from: 2020-10-24
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h

    # storage_config:
    #   tsdb_shipper:
    #     active_index_directory: /var/loki/tsdb-shipper-active
    #     cache_location: /var/loki/tsdb-shipper-cache
    #   filesystem:
    #     directory: /var/loki/chunks

    # limits_config:
    #   reject_old_samples: true
    #   reject_old_samples_max_age: 168h