# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: prometheus-config
#   namespace: shopmicro
# data:
#   prometheus.yml: |
#     global:
#       scrape_interval: 15s
#       evaluation_interval: 15s

#     scrape_configs:
#       - job_name: 'kubernetes-services'
#         static_configs:
#           - targets: ['backend:3001']
#             labels:
#               service: backend
#           - targets: ['frontend:3000']
#             labels:
#               service: frontend
#           - targets: ['ml-service:3002']
#             labels:
#               service: ml-service

#       # Prometheus itself
#       - job_name: 'prometheus'
#         static_configs:
#           - targets: ['localhost:9090']


apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: shopmicro
data:
  prometheus.yml: |
    global:
      scrape_interval: 30s
      evaluation_interval: 30s
      scrape_timeout: 25s

    scrape_configs:
      - job_name: 'shopmicro-services'
        static_configs:
          # - targets: ['frontend.shopmicro.svc.cluster.local:3000']
          #   labels:
          #     service: frontend
          #     environment: shopmicro
          - targets: ['backend.shopmicro.svc.cluster.local:3001']
            labels:
              service: backend
              environment: shopmicro
          # - targets: ['ml-service.shopmicro.svc.cluster.local:3002']
          #   labels:
          #     service: ml-service
          #     environment: shopmicro

      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
