apiVersion: v1
kind: Service
metadata:
  name: alloy
  namespace: shopmicro
  labels:
    app: alloy
spec:
  selector:
    app: alloy
  ports:
  - port: 4318
    targetPort: 4318
    name: otlp
  type: ClusterIP

# apiVersion: v1
# kind: Service
# metadata:
#   name: alloy
#   namespace: shopmicro
# spec:
#   selector:
#     app: alloy
#   ports:
#   - port: 4318
#     targetPort: 4318