apiVersion: v1
kind: Service
metadata:
  name: mimir
  namespace: shopmicro
  labels:
    app: mimir
spec:
  selector:
    app: mimir
  ports:
  - port: 9009
    targetPort: 9009
    name: mimir
    protocol: TCP
  type: ClusterIP
