apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: shopmicro
  labels:
    app: tempo
spec:
  selector:
    app: tempo
  ports:
  - port: 3200
    targetPort: 3200
    name: http
    protocol: TCP
  - port: 4318
    targetPort: 4318
    name: otlp
    protocol: TCP
  type: ClusterIP
